### PR TITLE
Fix underlinking with lld (missing -lm)

### PR DESCRIPTION
**Pull request by thesamesam**
We need to explicitly search for and link with -lm if needed by libc for math libraries like `log` and `sin`:
```
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: sin
>>> referenced by ../.libs/libSDL_sound.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: log
>>> referenced by ../.libs/libSDL_sound.so
```

It turns out Gentoo has actually had a patch for this since 2012 (mea culpa!) but it never made its way upstream.

We're already using libtool, so just use the macro it provides for this purpose.

Signed-off-by: Sam James <sam@gentoo.org>

### CODE REVIEW

**Comment by sezero** [comment]
Thanks

**Comment by icculus** [comment]
Do we just want to use SDL_sin and SDL_log instead?

**Comment by sezero** [comment]
No: this is stable-1.0 branch where we still support SDL-1.2 with SDL2 being optional.

**Comment by sezero** [comment]
> @sezero if/when you merge, would you mind handling the autoreconf part?

Done as of https://github.com/icculus/SDL_sound/commit/0f2fd4f3a6a8fb7823c202eafa6bcade5985bff2

**Comment by thesamesam** [comment]
Thank you!

**Pull request merged**
