### PR TITLE
cmake: libraries cannot link to SDL2::SDL2main (through SDL2_LIBRARIES)

### LINKED ISSUE #72: CMake warning: Policy CMP0048 is not set
hi, this is really minor, is more a question really. Currently a warning is being generated in CMake versions 3 and above.

Most CMake projects I see use the version like this

```
project(SDL_sound 
    VERSION 2.0.1
    LANGUAGES C)
```

But SDL_sound uses like this

```
project(SDL_sound C)
set(SDLSOUND_VERSION 2.0.1)
```

But this means the `PROJECT_VERSION` and related variables would be empty. Is there any reason for this particular approach?

### LINKED ISSUE #75: CI mingw build runs failing
The CI mingw build runs have been failing lately: See, e.g.:
https://github.com/icculus/SDL_sound/actions/runs/3075247792/jobs/4968503132

This probably has something to do with SDL2-2.24.0 cmake'ry?
@madebr?

### PR DESCRIPTION
**Pull request by madebr**
With MinGW when linking to `SDL2::SDL2main`, `-Wl,-u,main` is passed to the linker.
This was done to avoid the requriement of adding `-lmingw32 -lSDL2` + it also allows normal CMake targets.

Fixes #75
Fixes #72

CI: https://github.com/madebr/SDL_sound/actions/runs/3078892981

### CODE REVIEW

**Comment by ericoporto** [comment]
Why the new `if` cases in [`83bec53`](https://github.com/icculus/SDL_sound/pull/76/commits/83bec53c5c59f0d90d8da1a01903e5e3dc0f9a65), is there any reason to not just rely in `SDL2_LIBRARIES` and similar variables?

**Comment by madebr** [comment]
`SDL2_LIBRARIES` was used before.
On MinGW, it links to both SDL2::SDL2 and SDL2::SDL2main.
The `SDL2::SDL2main` target adds the linker flag `-Wl,-u,main` (=mark main as undefined).

Since shared libraries usually don't have a main function, this causes link errors.
So use `SDL2::SDL2` instead.

But now you make me start thinking about it.
Perhaps we should add logic (using generator expressions) to only add `-Wl,-u,main` when building an executable.

**Comment by sezero** [comment]
Do we still need any parts of the following after this?
https://github.com/icculus/SDL_sound/blob/main/CMakeLists.txt#L28-L37

**Comment by madebr** [comment]
> Do we still need any parts of the following after this? https://github.com/icculus/SDL_sound/blob/main/CMakeLists.txt#L28-L37

Yes, for compatibility with older SDL2 versions.

**Comment by sezero** [comment]
OK, thanks!

**Comment by madebr** [comment]
https://github.com/libsdl-org/SDL/pull/6260 addresses this.
If that patch would have been in 2.24, then this pr wouldn't have been necessary...

**Comment by sezero** [comment]
> [libsdl-org/SDL#6260](https://github.com/libsdl-org/SDL/pull/6260) addresses this. If that patch would have been in 2.24, then this pr wouldn't have been necessary...

Have you cherry-picked that into release-2.24.x branch?

**Comment by sezero** [comment]
> > [libsdl-org/SDL#6260](https://github.com/libsdl-org/SDL/pull/6260) addresses this. If that patch would have been in 2.24, then this pr wouldn't have been necessary...
> 
> Have you cherry-picked that into release-2.24.x branch?

Sorry, failed noticed that it's a new pull request.

**Pull request merged**
